### ISSUE TITLE
VMware plugin error with vSphere 8

### ISSUE THREAD

**Issue by remche** [bareos/bareos#1802]
### Environment ###

- bareos (all components and vmware plugin/vadp dumper) **23.0.3~pre104.aaf825630-84**
- bareos-vmware-vix-disklib **8.0.2-22388865**
- ESXi **8.0 U2b - 23305546**
- vCenter 8.0.2.00200 (Build: 23319993) 

### Steps to reproduce

1. After configuring plugin, add a VM Filesest as stated in documentation

### Expected results

Backup to finish consistently.

### Actual results

Backup will mostly fail on large VM disk with the following log.

Is there any known issue with vSphere 8 ?

### Environment

```markdown
- OS: `Ubuntu 22.04.4 LTS`
- ESXi **8.0 U2b - 23305546**
- vCenter 8.0.2.00200 (Build: 23319993)
```

### Relevant log output

```shell
-5570-7636-04320120b960/resif-loki.vmdk
02-mai 15:42 bareos-sd JobId 7: Fatal error: TLS read/write failure.: ERR=error:0A000119:SSL routines::decryption failed or bad record mac
02-mai 15:42 osug-bareos-test-fd JobId 7: Fatal error: TLS read/write failure.: ERR=error:0A0003FC:SSL routines::sslv3 alert bad record mac
02-mai 15:42 osug-bareos-test-fd JobId 7: Error: lib/bsock_tcp.cc:418 Wrote 49478 bytes to Storage daemon:osug-bareos-test:9103, but only 0 acce
pted.
02-mai 15:42 osug-bareos-test-fd JobId 7: Fatal error: filed/backup.cc:1405 Network send error to SD. ERR=Input/output error
02-mai 15:42 bareos-sd JobId 7: Error: lib/bsock_tcp.cc:614 Read expected 164210 got 147452 from client:127.0.0.1:9103
02-mai 15:42 bareos-sd JobId 7: Fatal error: stored/append.cc:445 Error reading data header from FD. ERR=Input/output error
02-mai 15:42 bareos-sd JobId 7: Releasing device "FileStorage" (/var/lib/bareos/storage).
02-mai 15:42 bareos-sd JobId 7: Elapsed time=00:00:43, Transfer rate=202.9 M Bytes/second
02-mai 15:44 osug-bareos-test-fd JobId 7: Fatal error: python3-fd-mod: check_dumper(): bareos_vadp_dumper returncode: 15 error output:

02-mai 15:44 osug-bareos-test-fd JobId 7: Fatal error: python3-fd-mod: plugin_io[IO_CLOSE]: bareos_vadp_dumper returncode: 15 error output:

02-mai 15:44 osug-bareos-test-fd JobId 7: Error: lib/bsock_tcp.cc:455 Socket has errors=1 on call to Storage daemon:osug-bareos-test:9103
02-mai 15:44 osug-bareos-test-fd JobId 7: python3-fd-mod: Cleaning up snapshot BareosTmpSnap_jobId_7 from VM resif-loki
```

**Comment by sduehr** [comment]
What is the size of your "large VM disk"?
I've seen successful jobs on vSphere 8 with 180GB disk, no issues with vSphere 8 that I'd know.

Could you please add the following plugin option to the fileset:

`vadp_dumper_verbose=yes`

and then run the job again.
That will produce a detailed log of `bareos_vadp_dumper` in `/var/log/bareos/` on the system running bareos-fd.

I suspect that bareos_vadp_dumper error with returncode 15 is the root cause, but that's logged at 15:44 while the other errors occured already at 15:42, so the bareos_vadp_dumper error could also be a subsequent error

**Comment by remche** [comment]
@sduehr thanks for quick reply and your suggestion.

> What is the size of your "large VM disk"? I've seen successful jobs on vSphere 8 with 180GB disk, no issues with vSphere 8 that I'd know.

It'as 200GB disk. We had no issue on our old 6.7 vSphere infrastructure.

[bareos_vadp_dumper.8-27239.log](https://github.com/bareos/bareos/files/15197782/bareos_vadp_dumper.8-27239.log)  file (redacted) does not seems to show root cause.

**Comment by sduehr** [comment]
Thanks, I've checked bareos_vadp_dumper and it only exits with returncode 15 if it was terminated by signal 15.
So it's probably a problem of the bareos-sd or communication between bareos-fd and bareos-sd.

**Comment by remche** [comment]
Thanks. FYI, it's an all-in-one setup with a local storage.

**Comment by sduehr** [comment]
As you said "mostly fail", so you have seen that job terminate successfully. That's why I don't think this is an issue of the VMware Plugin. The `TLS read/write failure` errors reported by bareos-sd and bareos-fd result from this code part:
https://github.com/bareos/bareos/blob/8be3e4b734fbe0b6976183d06e28f2c9d1dca7c4/core/src/lib/tls_openssl_private.cc#L323-L354

So this error message is just reported back from openssl. This could be caused by network problems or even by faulty memory, as reported in the following case which is not related to Bareos:
https://xcp-ng.org/forum/topic/7463/ssl-routines-ssl3_get_record-decryption-failed-or-bad-record-when-runing-full-backup/9

**Comment by remche** [comment]
Thanks for you suggestions. I will dig into this and keep you updated.
