### ISSUE TITLE
All jobs hang at "Extended attribute support is enabled"

### ISSUE THREAD

**Issue by 9manloon** [bareos/bareos#1812]
### Bareos component version

Bareos version 21.0.0

### Steps to reproduce

I have only one system. When we start a job, it hangs at "ACL support is enabled" and "Extended attribute support is enabled".

### Expected results

Expect it find a volume and back up

### Actual results

It hangs at "ACL support is enabled" and "Extended attribute support is enabled" forever.

### Environment

```markdown
NAME="Oracle Linux Server"
VERSION="8.6"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:6:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"
```

**Comment by bruno-at-bareos** [comment]
Hello, maybe you want to use a supported version 21x is outdated since a while (except for subscription customer who have access to latest 21.1.9). You may want to upgrade to current version 23.0.3~pre. first

You really need to provide a joblog eventually a trace if you want to have help. Otherwise, use the user mailing list to get help

**Comment by bruno-at-bareos** [comment]
Closing due to missing information and no return
