### ISSUE TITLE
mark command does not accept full path on windows

### ISSUE THREAD

**Issue by arogge** [bareos/bareos#1844]
In restore mode, the mark command does not accept a full path including drive letter.
After chaning into the drive letter first, the full path is accepted:
```
$ mark C:/src/binary/systemtests/tests/restore/tmp/data/build/src/tests/bregtest
No files marked.
$ cd C:
cwd is: C:/
$ mark src/binary/systemtests/tests/restore/tmp/data/build/src/tests/bregtest
1 file marked.

```

It would make sense to also accept the full path here.

**Comment by sebsura** [comment]
The mark command handles three types of paths
1. simple (relative) paths -- these are just file names, i.e. paths that do not contain '/'.  These are always treated as relative.
2. complex relative paths -- these are paths containing '/', which do not start with '/'.
3. complex absolute paths
The reason that `mark C:` works, is that its treated as a simple path and so uses a different code path from complex paths, where it only compares the given path with the name of each of the current nodes children, and marks every matching child:
https://github.com/bareos/bareos/blob/d815387f80733a0ab72cf1306c40e95d11c8a58c/core/src/dird/ua_tree.cc#L476-L482

But since `C:/directory` (or just `C:/`) contains `/` but does not begin with one, it is treated as a complex _relative_ path.  The way this works is that first the absolute path is created by appending the parent path to the current one:
https://github.com/bareos/bareos/blob/d815387f80733a0ab72cf1306c40e95d11c8a58c/core/src/dird/ua_tree.cc#L448-L457
In our case the parent node is just the root node, so its path is `/` leaving us with the absolute path
`/C:/...` which obviously does not exist.

One avenue of fixing this would be to ensure that the root node always has an empty path.  It seems like this was the plan all along acording to some comments, but maybe not implemented 100%:
https://github.com/bareos/bareos/blob/d815387f80733a0ab72cf1306c40e95d11c8a58c/core/src/lib/tree.cc#L357-L363

**Comment by sebsura** [comment]
push to @pstorz windows branch
