### ISSUE TITLE
Cannot login to the WebUI anymore since the last update

### ISSUE THREAD

**Issue by lpwevers** [bareos/bareos#1957]
### Bareos component version

shenhe:~ # bareos-fd --version
23.0.4~pre219.fcc1a62ef
shenhe:~ # bareos-dir --version
23.0.4~pre219.fcc1a62ef
shenhe:~ # bareos-sd --version
23.0.4~pre219.fcc1a62ef
shenhe:~ # bconsole --version
23.0.4~pre219.fcc1a62ef

### Steps to reproduce

Try to login to the WebUI

### Expected results

Succesful login

### Actual results

An error message stating: "Please provide a director, username and password."

### Environment

```markdown
shenhe:~ # cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.6"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.6"
PRETTY_NAME="openSUSE Leap 15.6"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.6"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

### Anything else?

This setup has been working for over two years now. All of a sudden this error is displayed when trying to login to the WebUI. There were no configuration changes whatsoever over the past few months. It looks like it happened with the latest update, but I can't downgrade to verify this.

**Comment by joergsteffens** [comment]
I just verified, that it is no related to the stricter ACL handling from 23.0.4 (see https://github.com/bareos/bareos/blob/Release/23.0.4/CHANGELOG.md).
No, it is not. Also insufficient ACL permissions would lead to an other error message.

So there must be some other reason for this.

**Comment by lpwevers** [comment]
Hmm, ok, if it's not that, can you please point me to the logfiles I should be investigating? Can't seem to find any errors there. Or how to put the webui in debug mode, so I can get more detailed information.

**Comment by arogge** [comment]
First of all: does your director run (i.e. can you connect with `bconsole`)? Does it work with the same credentials the webui uses (using the console defined for the webui)?

If that both works, a look at the logfile that php-fpm writes should  show any errors that happen on the PHP side of the webui. As I'm not too fluent with SUSE, I can't tell you the path of that file - you'll have to figure that out yourself.

**Comment by lpwevers** [comment]
Thanks. You made me look in the right place. It seems that SUSE was kind enough to change something in the apparmor profiles blocking php-fpm. Running
`aa-complain '/etc/apparmor.d/php-fpm'`

fixed the issue for me

**Comment by pi-2007** [comment]
Hello,

thank you Ipwevers. Just to complement and help others finding the solution: the same happens when upgrading to Ubuntu 24.04 (or Ubuntu 22.04 - I did both one after another from 20.04, so no sure where the apparmor changes occurred).

I also had issues installing php8.3-fpm with error `kernel: audit: type=1400 audit(1732697859.019:135633): apparmor="DENIED" operation="sendmsg" class="file" profile="php-fpm" name="/run/systemd/notify" pid=192524 comm="php-fpm8.3" requested_mask="w" denied_mask="w" fsuid=0 ouid=0`

The solution (adapt local apparmor file for php-fpm) is described here: https://askubuntu.com/questions/1529224/php8-3-fpm-installation-fails-with-post-installation-script-error

However, maybe none of that is needed as apparmor needs to be set to complain for php-fpm? (otherwise no login is possible).
